"""Writes reports/shap_interactions.md from the Stage 4 tables (no hand-typed numbers)."""
import pandas as pd

from src.config import ROOT, load_config


def pct(x: float) -> str:
    return f"{100 * x:.1f}%"


def write() -> str:
    cfg = load_config()
    T = cfg["paths"]["tables"]
    rank = pd.read_csv(T / "shap_interaction_ranking.csv").head(cfg["shap"]["top_pairs"])
    run = pd.read_csv(T / "shap_run.csv").iloc[0]
    log = pd.read_csv(T / "interaction_selection_log.csv")
    acc = pd.read_csv(T / "interaction_accepted.csv")
    gap = pd.read_csv(T / "gap_closed.csv").iloc[0]
    ae_a = pd.read_csv(T / "two_way_ae_summary_glm_a.csv")
    ae_b = pd.read_csv(T / "two_way_ae_summary_glm_b.csv")
    comp = pd.read_csv(T / "frequency_model_comparison.csv").set_index("model")
    not_tr = pd.read_csv(T / "interaction_not_translated.csv")
    region = pd.read_csv(T / "region_bm_signal_by_step.csv")
    expo = pd.read_csv(T / "interaction_exposure_check.csv")
    b12p = pd.read_csv(T / "b12_profile.csv").set_index("group")

    pairs = ", ".join(f"{r.feature_1} x {r.feature_2}" for r in rank.itertuples())
    n_bm_age = int(sum(("BonusMalus" in (r.feature_1, r.feature_2)) or ("DrivAge" in (r.feature_1, r.feature_2))
                       for r in rank.itertuples()))
    h_lead = rank.loc[rank["friedman_h2"].idxmax()]
    lines = [
        "# GBM interaction findings and GLM revision",
        "",
        "*Generated by `src/interactions/narrative.py` from `reports/tables/`. Rules and evidence: DECISIONS D018, D023 to D027.*",
        "",
        "## What the GBM found",
        "",
        f"SHAP interaction values for the tuned GBM, on {int(run.rows):,} learn policies stratified by claim indicator, "
        f"rank these pairs highest: {pairs}. {n_bm_age} of the {len(rank)} involve BonusMalus or driver age. "
        f"Friedman's H-statistic puts {h_lead.feature_1} x {h_lead.feature_2} first as well. "
        "Under French bonus-malus rules the coefficient starts at 1.00 (100 here) and falls 5% a year without claims "
        "(Code des assurances, art. A121-1), so one BonusMalus level means a novice at 25 but a recent claimant at 65.",
        "",
        "## Which effects are real",
        "",
        "Two-way tables of observed claims against out-of-fold predictions on learn data; mean z^2 near 1 means no pattern left.",
        "",
        "| Pair | vs GLM-A | vs GLM-B |",
        "|---|---|---|",
    ]
    for (_, a), (_, b) in zip(ae_a.iterrows(), ae_b.iterrows()):
        lines.append(f"| {a.factor_1.split('_')[0]} x {a.factor_2.split('_')[0]} | {a.mean_z_squared:.2f} | {b.mean_z_squared:.2f} |")
    lines += [
        "",
        "Rejected untested (no excess over noise): "
        + "; ".join(f"{r.pair} ({int(r.cells_abs_z_gt_1_96)} significant cells, {r.expected_by_chance:.1f} expected)" for r in not_tr.itertuples()) + ".",
        "",
        "## What survived",
        "",
        "Tariff-friendly forms were added to GLM-A one pair at a time, in an owner-set order, on the shared CV folds. Accepted:",
        "",
    ]
    for r in acc.itertuples():
        row = log[(log.step == r.step) & (log.candidate == r.accepted)].iloc[0]
        lines.append(f"- **{r.accepted}**: {row.description}. Improved all 5 folds; {pct(r.share_of_gap)} of the gap.")
    rejected = log[~log.candidate.isin(acc.accepted)].sort_values("step").groupby("candidate").tail(1)
    lines += ["", "Rejected or not tested:", ""]
    for r in rejected.itertuples():
        if isinstance(getattr(r, "not_tested_reason", None), str):
            lines.append(f"- {r.candidate}: not tested, {r.not_tested_reason}.")
            continue
        if r.passes:
            lines.append(f"- {r.candidate}: passed, but another form of the same pair improved more.")
            continue
        reasons = []
        if not r.rule2_all_folds:
            reasons.append(f"{int(r.folds_improved)} of 5 folds")
        if not r.rule3_materiality:
            reasons.append(f"{pct(r.share_of_gap)} of gap, below 5% floor")
        if not r.sign_stable_all_folds:
            reasons.append("unstable signs across folds")
        if r.sign_stable_all_folds and not r.rule4_stable_sensible:
            reasons.append(f"multiplier up to {r.multiplier_p99:.2f}, above 2.0")
        lines.append(f"- {r.candidate}: " + "; ".join(reasons) + ".")
    lines += [
        "",
        "## Share of GBM lift captured",
        "",
        f"GLM-B closes {pct(gap.cv_gap_closed_by_glm_b)} of the CV deviance gap between GLM-A and the GBM "
        f"({pct(gap.holdout_gap_closed_by_glm_b)} on holdout) with "
        f"{int(comp.loc['GLM-B (proposed tariff)', 'n_params'] - comp.loc['GLM-A (current tariff)', 'n_params'])} extra parameters. "
        f"Holdout Gini: GLM-A {comp.loc['GLM-A (current tariff)', 'holdout_gini']:.3f}, "
        f"GLM-B {comp.loc['GLM-B (proposed tariff)', 'holdout_gini']:.3f}, GBM {comp.loc['GBM (LightGBM Poisson)', 'holdout_gini']:.3f}. "
        f"The largest pattern left is BonusMalus x Region. Its residual mean z^2 goes from "
        f"{region.mean_z_squared.iloc[0]:.2f} under GLM-A to " + ", ".join(
            f"{r.mean_z_squared:.2f} {r.model.replace('diagnostic: ', '')}" for r in region.iloc[1:].itertuples()) + ".",
        "",
        "## B12 and short exposure",
        "",
        f"B12 policies are shorter (mean exposure {b12p.loc['B12', 'mean_exposure']:.2f} against "
        f"{b12p.loc['other brands', 'mean_exposure']:.2f}) and newer ({pct(b12p.loc['B12', 'share_vehage_le_1'])} aged 0-1 against "
        f"{pct(b12p.loc['other brands', 'share_vehage_le_1'])}). Refitting GLM-B with log(exposure) as a free covariate "
        "moves the B12 coefficients by a factor of "
        + " and ".join(f"{r.ratio_free_to_offset:.2f}" for r in expo[expo.term.str.startswith('b12')].itertuples())
        + ". " + ("The effect shrinks materially, so it is likely driven partly by short-exposure policies (hypothesis, unverified)."
                  if (expo[expo.term.str.startswith('b12')].ratio_free_to_offset < 0.75).any() else
                  "The shrinkage is under 25%, so the effect is not mainly a short-exposure artefact."),
    ]
    text = "\n".join(lines) + "\n"
    (ROOT / "reports" / "shap_interactions.md").write_text(text)
    return text


if __name__ == "__main__":
    t = write()
    print(t)
    print(len(t.split()), "words")
