"""Writes reports/shap_interactions.md from the Stage 4 tables (no hand-typed numbers)."""
import pandas as pd

from src.config import ROOT, load_config


def pct(x: float) -> str:
    return f"{100 * x:.1f}%"


def write() -> str:
    cfg = load_config()
    T = cfg["paths"]["tables"]
    rank = pd.read_csv(T / "shap_interaction_ranking.csv").head(cfg["shap"]["top_pairs"])
    run = pd.read_csv(T / "shap_run.csv").iloc[0]
    log = pd.read_csv(T / "interaction_selection_log.csv")
    acc = pd.read_csv(T / "interaction_accepted.csv")
    gap = pd.read_csv(T / "gap_closed.csv").iloc[0]
    ae_a = pd.read_csv(T / "two_way_ae_summary_glm_a.csv")
    ae_b = pd.read_csv(T / "two_way_ae_summary_glm_b.csv")
    comp = pd.read_csv(T / "frequency_model_comparison.csv").set_index("model")
    not_tr = pd.read_csv(T / "interaction_not_translated.csv")

    pairs = ", ".join(f"{r.feature_1} x {r.feature_2}" for r in rank.itertuples())
    n_bm_age = int(sum(("BonusMalus" in (r.feature_1, r.feature_2)) or ("DrivAge" in (r.feature_1, r.feature_2))
                       for r in rank.itertuples()))
    h_lead = rank.loc[rank["friedman_h2"].idxmax()]
    lines = [
        "# GBM interaction findings and GLM revision",
        "",
        "*Generated by `src/interactions/narrative.py` from `reports/tables/`. Rules and evidence: DECISIONS D018, D023 to D027.*",
        "",
        "## What the GBM found",
        "",
        f"SHAP interaction values for the tuned GBM, on {int(run.rows):,} learn policies stratified by claim indicator, "
        f"rank these pairs highest: {pairs}. {n_bm_age} of the {len(rank)} involve BonusMalus or driver age. "
        f"Friedman's H-statistic puts {h_lead.feature_1} x {h_lead.feature_2} first as well. "
        "This fits how French bonus-malus works: the coefficient starts at 1.00 (100 here) and falls 5% a year "
        "without claims (Code des assurances, art. A121-1). The same BonusMalus therefore means a novice at 25 "
        "but a recent claimant at 65.",
        "",
        "## Which effects are real",
        "",
        "Each pair was checked against raw learn data: a two-way table of observed claims against out-of-fold "
        "predictions. A mean squared z-score near 1 means the model leaves no pattern.",
        "",
        "| Pair | vs GLM-A | vs GLM-B |",
        "|---|---|---|",
    ]
    for (_, a), (_, b) in zip(ae_a.iterrows(), ae_b.iterrows()):
        lines.append(f"| {a.factor_1.split('_')[0]} x {a.factor_2.split('_')[0]} | {a.mean_z_squared:.2f} | {b.mean_z_squared:.2f} |")
    lines += [
        "",
        "Not taken forward (no pattern in the data): " + ", ".join(not_tr["pair"]) + ".",
        "",
        "## What survived",
        "",
        "Candidates in tariff-friendly forms were added to GLM-A by forward selection on the shared CV folds. Accepted:",
        "",
    ]
    for r in acc.itertuples():
        row = log[(log.step == r.step) & (log.candidate == r.accepted)].iloc[0]
        lines.append(f"- **{r.accepted}**: {row.description}. Improved all 5 folds; {pct(r.share_of_gap)} of the gap.")
    rejected = log[~log.candidate.isin(acc.accepted)].sort_values("step").groupby("candidate").tail(1)
    lines += ["", "Rejected:", ""]
    for r in rejected.itertuples():
        reasons = []
        if not r.rule2_all_folds:
            reasons.append(f"{r.folds_improved} of 5 folds")
        if not r.rule3_materiality:
            reasons.append(f"{pct(r.share_of_gap)} of gap, below 5% floor")
        if not r.sign_stable_all_folds:
            reasons.append("unstable signs across folds")
        if r.sign_stable_all_folds and not r.rule4_stable_sensible:
            reasons.append(f"multiplier up to {r.multiplier_p99:.2f}, above 2.0")
        lines.append(f"- {r.candidate}: " + "; ".join(reasons) + ".")
    lines += [
        "",
        "## Share of GBM lift captured",
        "",
        f"GLM-B closes {pct(gap.cv_gap_closed_by_glm_b)} of the CV deviance gap between GLM-A and the GBM "
        f"({pct(gap.holdout_gap_closed_by_glm_b)} on holdout) with "
        f"{int(comp.loc['GLM-B (proposed tariff)', 'n_params'] - comp.loc['GLM-A (current tariff)', 'n_params'])} extra parameters. "
        f"Holdout Gini: GLM-A {comp.loc['GLM-A (current tariff)', 'holdout_gini']:.3f}, "
        f"GLM-B {comp.loc['GLM-B (proposed tariff)', 'holdout_gini']:.3f}, GBM {comp.loc['GBM (LightGBM Poisson)', 'holdout_gini']:.3f}. "
        "The largest pattern left is BonusMalus x Region, still visible in GLM-B residuals.",
    ]
    text = "\n".join(lines) + "\n"
    (ROOT / "reports" / "shap_interactions.md").write_text(text)
    return text


if __name__ == "__main__":
    t = write()
    print(t)
    print(len(t.split()), "words")
